import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider, Layout } from "antd";
import { Content, Footer, Header } from "antd/es/layout/layout";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              components: {
                Layout: {
                  colorBgBase: "#000",
                },
              },
            }}
          >
            <Layout style={{ minHeight: "100vh" }}>
              <NavBar />
              <Content style={{ alignItems: 'start' }}>{children}</Content>
              <Footer style={{ textAlign: "center" }}>
                Created By: Carlos Gil
              </Footer>
            </Layout>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
