import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Layout } from "antd";
import { Content, Footer } from "antd/es/layout/layout";
import NavBar from "@/components/NavBar";
import ConfigProviderWrapper from "@/components/ConfigProviderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigProviderWrapper>
            <Layout style={{ minHeight: "100vh" }}>
              <NavBar />
              <Content style={{ alignItems: "start" }}>{children}</Content>
              <Footer style={{ textAlign: "center" }}>
                Created By: Carlos Gil
              </Footer>
            </Layout>
          </ConfigProviderWrapper>
        </AntdRegistry>
      </body>
    </html>
  );
}
